src/NT/NewsBundle/Entity/News.php
<?php
namespace NT\NewsBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use NT\SEOBundle\SeoAwareInterface;
use NT\SEOBundle\SeoAwareTrait;
use NT\PublishWorkflowBundle\PublishWorkflowTrait;

/**
 * News's entity
 *
 * @ORM\Table(name="news")
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="NewsRepository")
 * @Gedmo\Loggable
 *
 */
class News implements SeoAwareInterface
{
    use SeoAwareTrait;
    use PublishWorkflowTrait;
    use \NT\FrontendBundle\Traits\SocialIconsTrait;
    use \A2lix\TranslationFormBundle\Util\Gedmo\GedmoTranslatable;

    /** @ORM\Id @ORM\GeneratedValue @ORM\Column(type="integer") */
    protected $id;

    /**
     * @Gedmo\Versioned
     * @Gedmo\Translatable
     * @ORM\Column(name="slug", type="string", length=255, nullable=true)
     */
    protected $slug;

    /**
     * @Gedmo\Versioned
     * @Gedmo\Translatable
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    protected $title;

    /**
     * @Gedmo\Versioned
     * @Gedmo\Translatable
     * @ORM\Column(name="simple_description", type="text", nullable=true)
     */
    protected $simpleDescription;

    /**
     * @Gedmo\Versioned
     * @Gedmo\Translatable
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    protected $description;

    /**
     * @Gedmo\Versioned
     * @ORM\Column(name="published_date", type="datetime")
     */
    protected $publishedDate;

    /**
     * @Gedmo\Versioned
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @Gedmo\Versioned
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    protected $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="\Application\Sonata\MediaBundle\Entity\Media")
     * @ORM\JoinColumn(name="image_id", referencedColumnName="id",  onDelete="SET NULL")
     */
    protected $image;

    /**
     * @ORM\ManyToOne(targetEntity="\Application\Sonata\MediaBundle\Entity\Gallery")
     * @ORM\JoinColumn(name="gallery_id", referencedColumnName="id",  onDelete="SET NULL")
     */
    protected $gallery;

    /**
     * @ORM\Column(name="is_homepage", type="boolean")
     */
    protected $isHomepage = false;

    /**
     * @ORM\Column(name="is_top", type="boolean")
     */
    protected $isTop = false;

    /**
     * @ORM\ManyToMany(targetEntity="NewsCategory", inversedBy="posts")
     * @ORM\JoinTable(name="news_categories_m2m")
     */
    protected $postsCategories;

    /**
     * @ORM\OneToMany(targetEntity="NT\NewsBundle\Entity\NewsTranslation", mappedBy="object", cascade={"persist", "remove"}, indexBy="locale")
     */
    protected $translations;

    public function __construct()
    {
        $this->translations = new ArrayCollection();
    }

    public function getRoute()
    {
        if ($this->getPostsCategories()->count() > 0) {
            return 'posts_category_post_view';
        } else {
            return 'post_without_category';
        }
    }

    public function getRouteParams($params = array())
    {
        return array_merge(array('slug' => $this->getSlug()), $params);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        if($this->title === NULL || strlen($this->title) == 0 && $this->translations !== null) {
            foreach ($this->translations as $translation) {
                if($translation->getTitle() && strlen($translation->getTitle()) != 0) {
                    return $translation->getTitle();
                }
            }
        }
        return $this->title;
    }

    public function setTitle($value)
    {
        $this->title = $value;
    }

    public function getSimpleDescription()
    {
        return $this->simpleDescription;
    }

    public function setSimpleDescription($value)
    {
        $this->simpleDescription = $value;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($value)
    {
        $this->description = $value;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug($value)
    {
        $this->slug = $value;
    }

    public function getPublishedDate()
    {
        return $this->publishedDate;
    }

    public function setPublishedDate($publishedDate)
    {
        $this->publishedDate = $publishedDate;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function __toString()
    {
        return $this->getTitle() ?: 'n/a';
    }

    /**
     * Gets the value of gallery.
     *
     * @return mixed
     */
    public function getGallery()
    {
        return $this->gallery;
    }

    /**
     * Sets the value of gallery.
     *
     * @param mixed $gallery the gallery
     *
     * @return self
     */
    public function setGallery($gallery)
    {
        $this->gallery = $gallery;
    }

    /**
     * Get the value of Is Homepage
     *
     * @return mixed
     */
    public function getIsHomepage()
    {
        return $this->isHomepage;
    }

    /**
     * Set the value of Is Homepage
     *
     * @param mixed isHomepage
     *
     * @return self
     */
    public function setIsHomepage($isHomepage)
    {
        $this->isHomepage = $isHomepage;

        return $this;
    }

    /**
     * Get the value of Is Top
     *
     * @return mixed
     */
    public function getIsTop()
    {
        return $this->isTop;
    }

    /**
     * Set the value of Is Top
     *
     * @param mixed isTop
     *
     * @return self
     */
    public function setIsTop($isTop)
    {
        $this->isTop = $isTop;

        return $this;
    }


    /**
     * Get the value of Posts Categories
     *
     * @return mixed
     */
    public function getPostsCategories()
    {
        return $this->postsCategories;
    }

    /**
     * Set the value of Posts Categories
     *
     * @param mixed postsCategories
     *
     * @return self
     */
    public function setPostsCategories($postsCategories)
    {
        $this->postsCategories = $postsCategories;

        return $this;
    }

}

src/NT/NewsBundle/Resources/views/Frontend/homepagePosts.html.twig
{% if posts is defined and posts is not null and posts|length %}
    <ul>
        {% for item in posts %}
            <li>
                <a href="{{ path('post_without_category', item.routeParams()) }}">
                    {{ item.title }}
                </a>
                <span class="meta-data">{{ item.publishedDate|date('d.m.Y') }}</span>
            </li>
        {% endfor %}
    </ul>
{% endif %}

src/NT/NewsBundle/Resources/views/Frontend/latestPosts.html.twig
<div class="widget-recent-posts widget">
    <h3 class="widgettitle">{{ 'latest_posts'|trans({}, 'messages')}}</h3>
    <ul>
        {% for item in posts %}
            <li class="clearfix">
                <a href="{{ path('post_without_category', item.routeParams()) }}" class="media-box post-image">
                    {% if item.translations[app.request.locale].image is defined and item.translations[app.request.locale].image is not null and item.translations[app.request.locale].image|length %}
                    {% thumbnail item.translations[app.request.locale].image, 'index' with {'title':item.translations[app.request.locale].title, 'alt':item.translations[app.request.locale].title, 'class':'img-thumbnail'} %}
                    {% endif %}
                </a>
                <div class="widget-blog-content">
                    <a href="{{ path('post_without_category', item.routeParams()) }}">
                        {{item.title}}
                    </a>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

src/NT/NewsBundle/Resources/views/Frontend/post_without_category.html.twig
{% extends '::base.html.twig' %}

{% import '::renderSocials.html.twig' as renderSocials %}

{% block main %}
    {% include '::headerImage.html.twig' with {'content':content} %}

    {% set haveSideBar = false %}
    {% if sideBar is defined and sideBar is not null and sideBar | length %}
        {% set haveSideBar = true %}
    {% endif %}

    <div class="main" role="main">
        <div id="content" class="content full">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        <header class="single-post-header clearfix">
                            <h2 class="post-title">{{ post.title }}</h2>
                        </header>
                        <article class="post-content">
                            <div class="post-meta meta-data">
                                <span>
                                    <i class="fa fa-calendar"></i>
                                    {{ 'published_at'|trans({}, 'messages')}} {{ post.publishedDate|date('d.m.Y') }}
                                </span>
                            </div>
                            {% if post.translations[app.request.locale].image is defined and post.translations[app.request.locale].image is not null and post.translations[app.request.locale].image|length %}
                                <div class="featured-image">
                                    {% thumbnail post.translations[app.request.locale].image, 'index' with {'title':post.translations[app.request.locale].title, 'alt':post.translations[app.request.locale].title} %}
                                </div>
                            {% endif %}
                            {% if post.description is defined and post.description is not null and post.description|length %}
                                {{ post.description|raw }}
                            {% endif %}
                        </article>
                    </div>

                    <div class="col-md-3 sidebar">
                        {% if haveSideBar %}
                            <div class="widget sidebar-widget">
                                <h3 class="widgettitle">
                                    {{ 'post_categories'|trans({}, 'messages')}}
                                </h3>
                                {{ sideBar|raw }}
                            </div>
                        {% endif %}
                        {% include 'NTNewsBundle:Frontend:latestPosts.html.twig' with {'posts': latestPosts} %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#
    {% include '::breadCrumbs.html.twig' with {'breadCrumbs': breadCrumbs} %}

    <section id="main">
        <div class="mainBody">
            <div class="wrapper">
                {% set haveSideBar = false %}
                {% if sideBar is defined and sideBar is not null and sideBar | length %}
                    {% set haveSideBar = true %}
                {% endif %}
                <div class="mainContent{% if haveSideBar == false %} full{% endif %}">
                    <h1 class="titleMain">{{ post.title }}</h1>

                    <p class="date">
                        <i class="iconDate"></i>{{ post.publishedDate|date('d.m.Y') }}</p>

                    {% if post.description is defined and post.description is not null and post.description | length %}
                        <article class="article">
                            {{ post.description|graw }}
                        </article>
                    {% endif %}

                    {% if post.getShareIcons is defined and post.getShareIcons is not null and post.getShareIcons | length %}
                        <div class="shareBar">
                            <p>{{ 'share'|trans({}, 'messages')}}</p>

                            <div class="socials socialsShare">
                                {{ renderSocials.renderSocials() }}
                            </div>
                            <!-- /.socials -->
                        </div>
                        <!-- /.shareBar -->
                    {% endif %}

                    {% if latestPosts is defined and latestPosts is not null and latestPosts | length %}
                        <div class="module moduleRelated">
                            <div class="moduleHead">
                                <p class="title">{{ 'inner_latest_news'|trans({}, 'messages')}}</p>

                                <div class="more">
                                    <a href="{{ path('posts_list') }}">{{ 'inner_news_see_all'|trans({}, 'messages')}}</a>
                                </div>
                            </div>
                            <!-- /.moduleHead -->

                            {% include 'NTNewsBundle:Frontend:latestPosts.html.twig' with {'posts': latestPosts} %}
                        </div>
                        <!-- /.module -->
                    {% endif %}
                </div>
                <!-- /.mainContent -->

                {% if haveSideBar %}
                    <aside class="sidebar">
                        <p class="titleAside">{{ content.title }}</p>

                        <nav class="navAside">
                            {{ sideBar|raw }}
                        </nav>
                        <!-- /.navAside -->
                    </aside>
                    <!-- /.sidebar -->
                {% endif %}
            </div>
            <!-- /.wrapper -->
        </div>
        <!-- /.mainBody -->
    </section>
    #}
{% endblock %}

src/NT/NewsBundle/Resources/views/Frontend/posts_categories_list.html.twig
{% extends '::base.html.twig' %}

{% import "::paginatorWithRouteAndSlug.html.twig" as pager %}

{% block main %}
    {% include '::headerImage.html.twig' with {'content':content} %}

    {% set haveSideBar = false %}
    {% if sideBar is defined and sideBar is not null and sideBar | length %}
        {% set haveSideBar = true %}
    {% endif %}

    <div class="main" role="main">
        <div id="content" class="content full">
            <div class="container">
                <div class="row">
                    <div class="{% if haveSideBar == true %}col-md-9{% else %}col-md-12{% endif %} posts-archive">
                        {% for item in posts %}
                            <article class="post">
                                <div class="row">
                                    <div class="col-md-4 col-sm-4">
                                        <a href="{{ path('post_without_category', item.routeParams()) }}">
                                            {% if item.translations[app.request.locale].image is defined and item.translations[app.request.locale].image is not null and item.translations[app.request.locale].image | length %}
                                                {% thumbnail item.translations[app.request.locale].image,
                                                'index' with {
                                                    'title': item.translations[app.request.locale].title,
                                                    'alt': item.translations[app.request.locale].title,
                                                    'class': 'img-thumbnail'
                                                } %}
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="col-md-8 col-sm-8">
                                        <h3>
                                            <a href="{{ path('post_without_category', item.routeParams()) }}">
                                                {{ item.title }}
                                            </a>
                                        </h3>
                                        <span class="post-meta meta-data">
                                            <span>
                                                <i class="fa fa-calendar"></i>
                                                {{ item.publishedDate|date('d.m.Y') }}
                                            </span>
                                        </span>
                                        {% if item.simpleDescription is defined and item.simpleDescription is not null and item.simpleDescription | length %}
                                            <p>{{item.simpleDescription}}</p>
                                        {% endif %}
                                        <p>
                                            <a href="{{ path('post_without_category', item.routeParams()) }}" class="btn btn-primary">
                                                {{ 'read_more'|trans({}, 'messages')}}
                                                <i class="fa fa-long-arrow-right"></i>
                                            </a>
                                        </p>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}

                        {% if posts is defined and posts | length %}
                            {{ pager.pager(posts, "posts_list") }}
                        {% endif %}
                    </div>

                    {% if haveSideBar %}
                        <div class="col-md-3 sidebar">
                            <div class="widget sidebar-widget">
                                <div class="sidebar-widget-title">
                                    <h3 class="widgettitle">
                                        {{ 'post_categories'|trans({}, 'messages')}}
                                    </h3>
                                </div>
                                {{ sideBar|raw }}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{#
    {% include '::breadCrumbs.html.twig' with {'breadCrumbs':breadCrumbs} %}

    <section id="main">
        {% if content.translations[app.request.locale].headerImage is defined and content.translations[app.request.locale].headerImage is not null and content.translations[app.request.locale].headerImage|length %}
            <div class="mainHead">
                <div class="wrapper">
                    <div class="bannerMain" style="background-image: url({% path content.translations[app.request.locale].headerImage, 'reference' %});"></div>
                </div><!-- /.wrapper -->
            </div><!-- /.mainHead -->
        {% endif %}

        <div class="mainBody">
            <div class="wrapper">
                {% set haveSideBar = false %}
                {% if sideBar is defined and sideBar is not null and sideBar|length %}
                    {% set haveSideBar = true %}
                {% endif %}
                <div class="mainContent{% if haveSideBar == false %} full{% endif %}">
                    <h1 class="titleMain">{{ content.title }}</h1>

                    {% if content.description is defined and content.description is not null and content.description|length %}
                        <article class="article">
                            {{ content.description|raw }}
                        </article>
                    {% endif %}

                    <div class="boxes boxesNews">
                        {% for item in posts %}
                            <div class="box boxWide">
                                <a href="{{ path('post_without_category', item.routeParams()) }}" class="photo" style="background-image: url({% if item.translations[app.request.locale].image is defined and item.translations[app.request.locale].image is not null and item.translations[app.request.locale].image|length %}
                                    {% path item.translations[app.request.locale].image, 'index' %}{% else %}'/assets/images/no-img.jpg'{% endif %});"></a>

                                <div class="content">
                                    <p class="date"><i class="iconDate"></i>{{ item.publishedDate|date('d.m.Y') }}</p>

                                    <p class="title"><a href="{{ path('post_without_category', item.routeParams()) }}">{{ item.title }}</a></p>

                                    {% if item.simpleDescription is defined and item.simpleDescription is not null and item.simpleDescription|length %}
                                        <div class="text">
                                            {{ item.simpleDescription|raw }}
                                        </div>
                                    {% endif %}

                                    <div class="more">
                                        <a href="{{ path('post_without_category', item.routeParams()) }}">{{ 'read_more'|trans({}, 'messages')}}</a>
                                    </div>
                                </div>
                            </div><!-- /.box -->
                        {% endfor %}
                    </div><!-- /.boxes -->

                    {% if posts is defined and posts|length %}
                        {{ pager.pager(posts, "posts_list") }}
                    {% endif %}
                </div><!-- /.mainContent -->

                {% if haveSideBar %}
                    <aside class="sidebar">
                        <p class="titleAside">{{ content.title }}</p>

                        <nav class="navAside">
                            {{ sideBar|raw }}
                        </nav><!-- /.navAside -->
                    </aside><!-- /.sidebar -->
                {% endif %}
            </div><!-- /.wrapper -->
        </div><!-- /.mainBody -->
    </section>
    #}
{% endblock %}

src/NT/NewsBundle/Resources/views/Frontend/posts_category_posts_list.html.twig
{% extends '::base.html.twig' %}

{% import "::paginatorWithRouteAndSlug.html.twig" as pager %}

{% block main %}
{% include '::headerImage.html.twig' with {'content':content} %}

{% set haveSideBar = false %}
{% if sideBar is defined and sideBar is not null and sideBar | length %}
    {% set haveSideBar = true %}
{% endif %}

<div class="main" role="main">
    <div id="content" class="content full">
        <div class="container">
            <div class="row">
                <div class="{% if haveSideBar == true %}col-md-9{% else %}col-md-12{% endif %} posts-archive">
                    {% for item in categoryPosts %}
                        <article class="post">
                            <div class="row">
                                <div class="col-md-4 col-sm-4">
                                    <a href="{{ path('post_without_category', item.routeParams()) }}">
                                        {% if item.translations[app.request.locale].image is defined and item.translations[app.request.locale].image is not null and item.translations[app.request.locale].image | length %}
                                            {% thumbnail item.translations[app.request.locale].image,
                                            'index' with {
                                                'title': item.translations[app.request.locale].title,
                                                'alt': item.translations[app.request.locale].title,
                                                'class': 'img-thumbnail'
                                            } %}
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col-md-8 col-sm-8">
                                    <h3>
                                        <a href="{{ path('post_without_category', item.routeParams()) }}">
                                            {{ item.title }}
                                        </a>
                                    </h3>
                                    <span class="post-meta meta-data">
                                        <span>
                                            <i class="fa fa-calendar"></i>
                                            {{ item.publishedDate|date('d.m.Y') }}
                                        </span>
                                    </span>
                                    {% if item.simpleDescription is defined and item.simpleDescription is not null and item.simpleDescription | length %}
                                        <p>{{item.simpleDescription}}</p>
                                    {% endif %}
                                    <p>
                                        <a href="{{ path('post_without_category', item.routeParams()) }}" class="btn btn-primary">
                                            {{ 'read_more'|trans({}, 'messages')}}
                                            <i class="fa fa-long-arrow-right"></i>
                                        </a>
                                    </p>
                                </div>
                            </div>
                        </article>
                    {% endfor %}

                    {% if posts is defined and posts | length %}
                        {{ pager.pager(posts, "posts_list") }}
                    {% endif %}
                </div>

                {% if haveSideBar %}
                    <div class="col-md-3 sidebar">
                        <div class="widget sidebar-widget">
                            <div class="sidebar-widget-title">
                                <h3 class="widgettitle">
                                    {{ 'post_categories'|trans({}, 'messages')}}
                                </h3>
                            </div>
                            {{ sideBar|raw }}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    {#
    {% include '::breadCrumbs.html.twig' with {'breadCrumbs':breadCrumbs} %}

    <section id="main">
        {% if postCategory.translations[app.request.locale].image is defined and postCategory.translations[app.request.locale].image is not null and postCategory.translations[app.request.locale].image|length %}
            <div class="mainHead">
                <div class="wrapper">
                    <div class="bannerMain" style="background-image: url({% path postCategory.translations[app.request.locale].image, 'reference' %});"></div>
                </div><!-- /.wrapper -->
            </div><!-- /.mainHead -->
        {% endif %}

        <div class="mainBody">
            <div class="wrapper">
                {% set haveSideBar = false %}
                {% if sideBar is defined and sideBar is not null and sideBar|length %}
                    {% set haveSideBar = true %}
                {% endif %}
                <div class="mainContent{% if haveSideBar == false %} full{% endif %}">
                    <h1 class="titleMain">{{ postCategory.title }}</h1>

                    {% if postCategory.description is defined and postCategory.description is not null and postCategory.description|length %}
                        <article class="article">
                            {{ postCategory.description|raw }}
                        </article>
                    {% endif %}

                    <div class="boxes boxesNews">
                        {% for item in categoryPosts %}
                            <div class="box boxWide">
                                <a href="{{ path(item.route, item.routeParams({'categorySlug':postCategory.slug})) }}" class="photo" style="background-image: url({% if item.translations[app.request.locale].image is defined and item.translations[app.request.locale].image is not null and item.translations[app.request.locale].image|length %}
                                    {% path item.translations[app.request.locale].image, 'index' %}{% else %}'/assets/images/no-img.jpg'{% endif %});"></a>

                                <div class="content">
                                    <p class="date"><i class="iconDate"></i>{{ item.publishedDate|date('d.m.Y') }}</p>

                                    <p class="title">
                                        <a href="{{ path(item.route, item.routeParams({'categorySlug':postCategory.slug})) }}">
                                            {{ item.title }}
                                        </a>
                                    </p>

                                    {% if item.simpleDescription is defined and item.simpleDescription is not null and item.simpleDescription|length %}
                                        <div class="text">
                                            {{ item.simpleDescription|raw }}
                                        </div>
                                    {% endif %}

                                    <div class="more">
                                        <a href="{{ path(item.route, item.routeParams({'categorySlug':postCategory.slug})) }}">
                                            {{ 'read_more'|trans({}, 'messages')}}
                                        </a>
                                    </div>
                                </div>
                            </div><!-- /.box -->
                        {% endfor %}
                    </div><!-- /.boxes -->

                    {% if categoryPosts is defined and categoryPosts|length %}
                        {{ pager.pager(categoryPosts, postCategory.route, postCategory.slug, 'categorySlug') }}
                    {% endif %}
                </div><!-- /.mainContent -->

                {% if haveSideBar %}
                    <aside class="sidebar">
                        <p class="titleAside">{{ content.title }}</p>

                        <nav class="navAside">
                            {{ sideBar|raw }}
                        </nav><!-- /.navAside -->
                    </aside><!-- /.sidebar -->
                {% endif %}
            </div><!-- /.wrapper -->
        </div><!-- /.mainBody -->
    </section>
    #}
{% endblock %}